language: node_js
node_js:
    - "lts/*"

# https://github.com/greenkeeperio/greenkeeper-lockfile
before_install:
    - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

install:
    - npm install

script:
  - npm run build
  - npm test
